language: php

matrix:
  fast_finish: true
  include:
    - 7.2
    - 7.3

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script: ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
