dist: xenial
language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache

services:
  - redis-server
  - mysql

before_install:
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE forge;'

install:
  - travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
  - cp ./laravel/.env.travis ./laravel/.env.travis
  - ./laravel/artisan key:generate
  - ./laravel/artisan migrate
  - ./laravel/artisan db:seed --class='ThirtyThree\Tests\Database\Seeds\DatabaseSeeder'

script: ./vendor/bin/phpunit --coverage-text
